//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.101.8.0
//     UI Plugin:   1.3701.9.0
//
//     Project:     MEP621_XPanel
//     Version:     1.0.0.0
//     Sdk:         CH5:2.11.1.2
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using System;
using System.Collections.Generic;
using System.Linq;

namespace MEP621_XPanel
{
    /// <summary>
    /// Common Interface for Root Contracts.
    /// </summary>
    public interface IContract
    {
        object UserObject { get; set; }
        void AddDevice(BasicTriListWithSmartObject device);
        void RemoveDevice(BasicTriListWithSmartObject device);

        /// <summary>
        /// Fires on ANY activity on the panel.
        /// </summary>
        event EventHandler<EventArgs> Activity;
    }

    /// <summary>
    /// Root contract giving access to top level project items such as Pages and global Widgets.
    /// </summary>
    public sealed class Contract : IContract, IDisposable
    {
        #region Components

        private ComponentMediator ComponentMediator { get; set; }

        public MEP621_XPanel.ILab0 Lab0 { get { return (MEP621_XPanel.ILab0)InternalLab0; } }
        private MEP621_XPanel.Lab0 InternalLab0 { get; set; }

        public MEP621_XPanel.ILab1 Lab1 { get { return (MEP621_XPanel.ILab1)InternalLab1; } }
        private MEP621_XPanel.Lab1 InternalLab1 { get; set; }

        public MEP621_XPanel.ILab2 Lab2 { get { return (MEP621_XPanel.ILab2)InternalLab2; } }
        private MEP621_XPanel.Lab2 InternalLab2 { get; set; }

        #endregion

        #region Construction and Initialization

        public Contract()
            : this(new List<BasicTriListWithSmartObject>().ToArray())
        {
        }

        public Contract(BasicTriListWithSmartObject device)
            : this(new [] { device })
        {
        }

        public Contract(BasicTriListWithSmartObject[] devices)
        {
            if (devices == null)
                throw new ArgumentNullException("Devices is null");

            ComponentMediator = new ComponentMediator();
            ComponentMediator.ConfigureActivityEvent(onActivity);

            InternalLab0 = new MEP621_XPanel.Lab0(ComponentMediator, 1);

            InternalLab1 = new MEP621_XPanel.Lab1(ComponentMediator, 2);

            InternalLab2 = new MEP621_XPanel.Lab2(ComponentMediator, 3);


            for (int index = 0; index < devices.Length; index++)
            {
                AddDevice(devices[index]);
            }
        }

        /// <summary>
        /// Fires on ANY activity on the panel.
        /// </summary>
        public event EventHandler<EventArgs> Activity;
        private void onActivity(GenericBase currentDevice, SmartObjectEventArgs args)
        {
            var handler = Activity;
            if (handler != null)
                handler(currentDevice, args);
        }
        #endregion

        #region Standard Contract Members

        public object UserObject { get; set; }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            InternalLab0.AddDevice(device);
            InternalLab1.AddDevice(device);
            InternalLab2.AddDevice(device);

        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            InternalLab0.RemoveDevice(device);
            InternalLab1.RemoveDevice(device);
            InternalLab2.RemoveDevice(device);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            InternalLab0.Dispose();
            InternalLab1.Dispose();
            InternalLab2.Dispose();

            ComponentMediator.Dispose(); 
        }

        #endregion
    }
}

